import type { TechDetail } from "./types";

/**
 * Reference content (pros / cons / getting-started) for each catalog tech,
 * keyed by the same id used in catalog.ts. Generated by the
 * generate-tech-details workflow (see scripts/gen-details.mjs).
 * Missing ids fall back to empty detail via getDetail().
 */
export const DETAILS: Record<string, TechDetail> = {
  "ai-gateway": {
    "pros": [
      "One API across many model providers",
      "Automatic fallbacks and provider failover",
      "Built-in observability and cost tracking"
    ],
    "cons": [
      "Adds a routing layer dependency",
      "Best paired with Vercel AI SDK"
    ],
    "getStarted": "npm i ai"
  },
  "ai-sdk": {
    "pros": [
      "Unified API across many LLM providers",
      "First-class streaming, tools, structured output",
      "Tight TypeScript and React integration"
    ],
    "cons": [
      "TypeScript and JavaScript ecosystem only",
      "Abstraction can hide provider-specific features"
    ],
    "getStarted": "npm i ai"
  },
  "angular": {
    "pros": [
      "Full-featured framework with everything included",
      "Strong conventions suit large enterprise teams",
      "First-class TypeScript and tooling support"
    ],
    "cons": [
      "Steep learning curve and heavy boilerplate",
      "Heavier than lighter SPA alternatives"
    ],
    "getStarted": "npm install -g @angular/cli && ng new my-app"
  },
  "app-stores": {
    "pros": [
      "Trusted, discoverable distribution to OS users",
      "Handles updates and payments for you",
      "Native install experience on each platform"
    ],
    "cons": [
      "Review delays and policy rejections",
      "Annual fees and platform revenue cut"
    ],
    "getStarted": "https://developer.apple.com/programs/enroll"
  },
  "astro": {
    "pros": [
      "Ships almost zero JavaScript by default",
      "Great for content and marketing sites",
      "Use any UI framework via islands"
    ],
    "cons": [
      "Less suited to highly interactive app UIs",
      "Island hydration adds mental overhead"
    ],
    "getStarted": "npm create astro@latest"
  },
  "auth0": {
    "pros": [
      "Enterprise SSO, SAML, and compliance built in",
      "Mature, battle-tested identity platform",
      "Extensive provider and protocol support"
    ],
    "cons": [
      "Expensive and complex for small projects",
      "Heavier configuration than drop-in alternatives"
    ],
    "getStarted": "npm install @auth0/nextjs-auth0"
  },
  "authjs": {
    "pros": [
      "Mature, battle-tested Next.js auth",
      "Large provider and adapter ecosystem",
      "Familiar for existing NextAuth apps"
    ],
    "cons": [
      "Now in maintenance mode, slower updates",
      "Best mainly for migrating existing apps"
    ],
    "getStarted": "npm install next-auth@beta"
  },
  "aws": {
    "pros": [
      "Widest service catalog and maximum control",
      "Scales to virtually any workload",
      "Mature, reliable global infrastructure"
    ],
    "cons": [
      "Steep operational and learning curve",
      "Easy to overspend without careful management"
    ],
    "getStarted": "npm i -g aws-cdk"
  },
  "babylonjs": {
    "pros": [
      "Full-featured 3D engine for the web",
      "Built-in physics, audio, and tooling",
      "Strong WebGPU and PBR support"
    ],
    "cons": [
      "Larger bundle than minimal libraries",
      "Smaller community than Three.js"
    ],
    "getStarted": "npm install @babylonjs/core"
  },
  "better-auth": {
    "pros": [
      "Framework-agnostic TypeScript auth you own",
      "Self-hosted with no vendor lock-in",
      "Modern default for new projects"
    ],
    "cons": [
      "Younger ecosystem than established options",
      "You run and maintain it yourself"
    ],
    "getStarted": "npx auth init"
  },
  "chroma": {
    "pros": [
      "Dead simple for local prototypes",
      "Open source and embeddable",
      "Minimal setup to start indexing"
    ],
    "cons": [
      "Not built for large-scale production",
      "Fewer enterprise features than rivals"
    ],
    "getStarted": "pip install chromadb"
  },
  "clap": {
    "pros": [
      "Fast, robust single-binary CLIs",
      "Derive macros make parsing declarative",
      "Excellent help, errors, and completions"
    ],
    "cons": [
      "Rust learning curve and compile times",
      "Heavier than minimal arg parsers"
    ],
    "getStarted": "cargo add clap --features derive"
  },
  "claude": {
    "pros": [
      "Strong reasoning and reliable tool use",
      "Industry-leading long context window",
      "Opus/Sonnet/Haiku tiers fit any budget"
    ],
    "cons": [
      "Usage-based pricing adds up at scale",
      "No open weights, fully hosted only"
    ],
    "getStarted": "pip install anthropic"
  },
  "clerk": {
    "pros": [
      "Prebuilt sign-in and user-management UI components",
      "Fastest path to production-ready login",
      "Strong Next.js and React integration"
    ],
    "cons": [
      "Pricing climbs quickly past free monthly active users",
      "Vendor lock-in on hosted user data"
    ],
    "getStarted": "npm install @clerk/nextjs"
  },
  "cloudflare": {
    "pros": [
      "Global edge hosting very cheap at scale",
      "Workers run close to every user",
      "Strong free tier and bandwidth"
    ],
    "cons": [
      "Workers runtime differs from full Node.js",
      "Some Node APIs need compatibility flags"
    ],
    "getStarted": "npm create cloudflare@latest"
  },
  "cobra": {
    "pros": [
      "Powers kubectl, gh, and Hugo",
      "Single self-contained binary distribution",
      "Generators, subcommands, and flags built in"
    ],
    "cons": [
      "More boilerplate than lighter CLI libraries",
      "Go knowledge required"
    ],
    "getStarted": "go install github.com/spf13/cobra-cli@latest"
  },
  "codemagic": {
    "pros": [
      "Framework-agnostic across Flutter, native, React Native",
      "Generous free macOS build minutes monthly",
      "Visual config plus codemagic.yaml for power users"
    ],
    "cons": [
      "Build minutes get pricey at scale",
      "Less seamless than EAS for Expo"
    ],
    "getStarted": "https://codemagic.io/signup"
  },
  "colab": {
    "pros": [
      "Free GPUs with zero local setup",
      "Shareable notebooks straight from Google Drive",
      "Pre-installed data and ML libraries"
    ],
    "cons": [
      "Sessions time out and reset state",
      "Free tier GPU access is not guaranteed"
    ],
    "getStarted": "https://colab.research.google.com"
  },
  "compose": {
    "pros": [
      "Modern declarative native Android UI",
      "Less boilerplate than XML layouts",
      "First-class Kotlin and Google support"
    ],
    "cons": [
      "Android-only, no cross-platform reach",
      "Steeper recomposition mental model for beginners"
    ],
    "getStarted": ""
  },
  "cpp": {
    "pros": [
      "Maximum performance and hardware control",
      "Powers engines, systems, and HPC",
      "Vast mature libraries and tooling"
    ],
    "cons": [
      "Manual memory management invites bugs",
      "Steep learning curve, complex build systems"
    ],
    "getStarted": "sudo apt-get install build-essential"
  },
  "csharp": {
    "pros": [
      "Mature, versatile, great tooling",
      "Powers .NET, Unity, and web",
      "Strong typing with modern features"
    ],
    "cons": [
      "Historically tied to Microsoft ecosystem",
      "Heavier than lightweight scripting options"
    ],
    "getStarted": "dotnet new console"
  },
  "css-modules": {
    "pros": [
      "Scoped plain CSS with zero runtime",
      "No dependencies, works in any bundler",
      "Familiar CSS with no new syntax"
    ],
    "cons": [
      "No utilities or design system included",
      "More manual work than utility frameworks"
    ],
    "getStarted": ""
  },
  "custom-jwt": {
    "pros": [
      "Full control with no external dependency",
      "No per-user cost or vendor lock-in",
      "Lightweight token auth inside your service"
    ],
    "cons": [
      "You own all security, rotation, and edge cases",
      "Easy to get subtly wrong"
    ],
    "getStarted": ""
  },
  "dart": {
    "pros": [
      "The language powering Flutter",
      "Fast hot reload, sound typing",
      "Compiles to native and JavaScript"
    ],
    "cons": [
      "Adoption mostly limited to Flutter",
      "Smaller ecosystem outside mobile"
    ],
    "getStarted": "brew install dart"
  },
  "dbt": {
    "pros": [
      "Brings version control and tests to SQL",
      "Reusable models, refs, and documentation",
      "Huge ecosystem and adapter support"
    ],
    "cons": [
      "Transformation only, not extraction or loading",
      "Warehouse compute costs can add up"
    ],
    "getStarted": "pip install dbt-core"
  },
  "django": {
    "pros": [
      "Batteries included: ORM, admin, and auth",
      "Mature, secure, and well documented",
      "Huge ecosystem and proven at scale"
    ],
    "cons": [
      "Opinionated and heavier for tiny services",
      "Async support less mature than FastAPI"
    ],
    "getStarted": "pip install django"
  },
  "duckdb": {
    "pros": [
      "Blazing fast analytics on one machine",
      "In-process, zero server to manage",
      "Queries Parquet and CSV directly"
    ],
    "cons": [
      "Single-node, not for concurrent OLTP",
      "Not a transactional application database"
    ],
    "getStarted": "pip install duckdb"
  },
  "electron": {
    "pros": [
      "Mature, battle-tested, huge ecosystem",
      "One codebase ships all desktop platforms",
      "Consistent Chromium rendering everywhere"
    ],
    "cons": [
      "Large bundles and high memory usage",
      "Bundles full Chromium with every app"
    ],
    "getStarted": "npx create-electron-app@latest my-app"
  },
  "expo": {
    "pros": [
      "One TypeScript codebase for iOS and Android",
      "Huge React ecosystem and fast iteration",
      "Managed builds and updates via EAS"
    ],
    "cons": [
      "Some native modules need custom dev builds",
      "Bundle size larger than fully native apps"
    ],
    "getStarted": "npx create-expo-app@latest"
  },
  "expo-eas": {
    "pros": [
      "Cloud builds without local Xcode or Android setup",
      "Submits straight to App Store and Play",
      "Over-the-air updates skip store review"
    ],
    "cons": [
      "Free tier build queues can be slow",
      "Costs add up at higher build volumes"
    ],
    "getStarted": "npm install -g eas-cli && eas build:configure"
  },
  "express": {
    "pros": [
      "Ubiquitous with a massive ecosystem",
      "Minimal, flexible, easy to learn",
      "Tons of middleware and tutorials"
    ],
    "cons": [
      "Unopinionated, so structure is up to you",
      "Aging design, weaker native TypeScript support"
    ],
    "getStarted": "npm install express"
  },
  "fastapi": {
    "pros": [
      "Fast with first-class typing and validation",
      "Automatic OpenAPI and interactive docs",
      "Async support and clean modern syntax"
    ],
    "cons": [
      "Smaller batteries-included scope than Django",
      "ASGI deployment adds operational complexity"
    ],
    "getStarted": "pip install \"fastapi[standard]\""
  },
  "fastlane": {
    "pros": [
      "Automates signing, building, and store uploads",
      "Open source with huge plugin ecosystem",
      "Works in any CI, no lock-in"
    ],
    "cons": [
      "Ruby toolchain setup can be finicky",
      "Steeper learning curve than hosted CI"
    ],
    "getStarted": "brew install fastlane"
  },
  "firebase": {
    "pros": [
      "Realtime sync with offline-first clients",
      "Generous client SDKs across platforms",
      "Fast to ship with no backend"
    ],
    "cons": [
      "Limited querying and no real joins",
      "Costs and lock-in grow with scale"
    ],
    "getStarted": "npm i firebase"
  },
  "firebase-auth": {
    "pros": [
      "Easy multi-platform auth across web and mobile",
      "Many social and phone login providers",
      "Mature, free-tier-friendly Google-backed service"
    ],
    "cons": [
      "Locks you into the Google Firebase ecosystem",
      "Limited control over custom auth flows"
    ],
    "getStarted": "npm install firebase"
  },
  "flutter": {
    "pros": [
      "Single Dart codebase with near-native performance",
      "Fully custom, consistent UI across platforms",
      "Excellent hot reload and tooling"
    ],
    "cons": [
      "Dart is less common than TypeScript",
      "Larger app size and non-native widgets"
    ],
    "getStarted": "flutter create my_app"
  },
  "fly": {
    "pros": [
      "Run containers close to users worldwide",
      "Full Docker control with global distribution",
      "Good for stateful and latency-sensitive apps"
    ],
    "cons": [
      "More ops knowledge than push-to-deploy platforms",
      "Occasional reliability complaints on smaller tiers"
    ],
    "getStarted": "curl -L https://fly.io/install.sh | sh"
  },
  "gdscript": {
    "pros": [
      "Built into Godot, zero setup",
      "Python-like and beginner friendly",
      "Tightly integrated with the editor"
    ],
    "cons": [
      "Only useful inside Godot",
      "Slower than compiled engine languages"
    ],
    "getStarted": ""
  },
  "gh-releases": {
    "pros": [
      "Free hosting for installers and binaries",
      "Pairs cleanly with Homebrew and CI",
      "Versioned, scriptable via the gh CLI"
    ],
    "cons": [
      "No auto-update mechanism for users",
      "Large binaries can hit storage limits"
    ],
    "getStarted": "gh release create v1.0.0"
  },
  "go": {
    "pros": [
      "Fast compiled single-binary deploys",
      "Simple language, easy to learn",
      "First-class concurrency with goroutines"
    ],
    "cons": [
      "Verbose error handling",
      "Generics still feel limited"
    ],
    "getStarted": "go mod init example.com/m"
  },
  "go-gin": {
    "pros": [
      "High-performance HTTP services in Go",
      "Compiles to a single fast binary",
      "Simple, lightweight, and well documented"
    ],
    "cons": [
      "Fewer batteries than full frameworks",
      "Manual wiring for validation and structure"
    ],
    "getStarted": "go get github.com/gin-gonic/gin"
  },
  "godot": {
    "pros": [
      "Free, open-source, no royalties",
      "Lightweight editor and fast iteration",
      "Friendly GDScript plus C# option"
    ],
    "cons": [
      "Smaller ecosystem than Unity or Unreal",
      "3D rendering trails the big engines"
    ],
    "getStarted": ""
  },
  "hf-spaces": {
    "pros": [
      "Free hosting for ML demos and apps",
      "Built-in Gradio and Streamlit support",
      "GPU tiers available when you need them"
    ],
    "cons": [
      "Free CPU spaces sleep when idle",
      "GPU hardware tiers are paid"
    ],
    "getStarted": "https://huggingface.co/new-space"
  },
  "hono": {
    "pros": [
      "Ultralight and extremely fast",
      "Runs anywhere including edge runtimes",
      "Clean TypeScript-first API"
    ],
    "cons": [
      "Smaller ecosystem than Express",
      "Minimal core means more wiring yourself"
    ],
    "getStarted": "npm create hono@latest"
  },
  "itch": {
    "pros": [
      "Indie-friendly with flexible pay-what-you-want",
      "Set your own revenue share",
      "Fast, low-friction publishing and updates"
    ],
    "cons": [
      "Much smaller audience than Steam",
      "Minimal built-in discovery and marketing"
    ],
    "getStarted": "https://itch.io/game/new"
  },
  "java": {
    "pros": [
      "Battle-tested across enterprise backends",
      "Massive ecosystem and talent pool",
      "Stable, performant JVM runtime"
    ],
    "cons": [
      "Verbose compared to modern languages",
      "Slower to adopt newer paradigms"
    ],
    "getStarted": "sdk install java"
  },
  "jupyter": {
    "pros": [
      "Interactive exploration with inline output",
      "Pandas ecosystem for data wrangling",
      "Ubiquitous standard for analysis sharing"
    ],
    "cons": [
      "Hidden state causes hard-to-reproduce bugs",
      "Poor fit for production code"
    ],
    "getStarted": "pip install jupyterlab pandas"
  },
  "kafka": {
    "pros": [
      "Durable, replayable event log at massive scale",
      "High throughput with strong ordering guarantees",
      "Huge ecosystem of connectors and stream tooling"
    ],
    "cons": [
      "Heavy operational burden to run and tune",
      "Overkill for simple queue or low-volume needs"
    ],
    "getStarted": "docker run -p 9092:9092 apache/kafka"
  },
  "kotlin": {
    "pros": [
      "First-class language for Android",
      "Concise, safer than Java",
      "Full Java interop and JVM ecosystem"
    ],
    "cons": [
      "Compile times slower than Java",
      "Multiplatform tooling still maturing"
    ],
    "getStarted": "sdk install kotlin"
  },
  "langchain": {
    "pros": [
      "Huge ecosystem of integrations and tools",
      "Works in both Python and JS",
      "Fast prototyping of LLM chains"
    ],
    "cons": [
      "Heavy abstractions can obscure behavior",
      "Frequent breaking API changes"
    ],
    "getStarted": "pip install -U langchain"
  },
  "langgraph": {
    "pros": [
      "Explicit graph control over agent flow",
      "Built-in state and checkpointing",
      "Good for stateful multi-step agents"
    ],
    "cons": [
      "Steeper learning curve than simple chains",
      "Overkill for basic single-shot calls"
    ],
    "getStarted": "pip install -U langgraph"
  },
  "llamaindex": {
    "pros": [
      "Purpose-built for RAG pipelines",
      "Many connectors for ingestion and indexing",
      "Strong retrieval and query abstractions"
    ],
    "cons": [
      "Less suited to non-RAG agent workflows",
      "Modular packages add setup overhead"
    ],
    "getStarted": "pip install llama-index"
  },
  "maui": {
    "pros": [
      "Single C# codebase for desktop and mobile",
      "Native controls and good performance",
      "Strong Visual Studio tooling"
    ],
    "cons": [
      "Smaller community, occasional rough edges",
      "Weaker Linux desktop support"
    ],
    "getStarted": "dotnet new maui"
  },
  "mongodb": {
    "pros": [
      "Flexible schemas suit evolving data",
      "Horizontal scaling via sharding built in",
      "Rich query and aggregation pipeline"
    ],
    "cons": [
      "Weak multi-document transactions versus SQL",
      "Easy to model data poorly"
    ],
    "getStarted": "npm i mongodb"
  },
  "mui": {
    "pros": [
      "Comprehensive, polished component library",
      "Material Design out of the box",
      "Mature, well-documented, large community"
    ],
    "cons": [
      "Hard to escape the Material look",
      "Larger bundle and styling-system overhead"
    ],
    "getStarted": "npm install @mui/material @emotion/react @emotion/styled"
  },
  "mysql": {
    "pros": [
      "Popular, mature, and widely understood",
      "Huge hosting and tooling support",
      "Fast and reliable for typical workloads"
    ],
    "cons": [
      "Fewer advanced features than PostgreSQL",
      "Stricter SQL and extension limitations"
    ],
    "getStarted": "docker run --name mysql -e MYSQL_ROOT_PASSWORD=pass -p 3306:3306 -d mysql"
  },
  "nestjs": {
    "pros": [
      "Opinionated structure scales with team size",
      "Built-in DI, modules, and testing",
      "Strong TypeScript and decorator support"
    ],
    "cons": [
      "Steeper learning curve and more boilerplate",
      "Heavier than needed for small APIs"
    ],
    "getStarted": "npm i -g @nestjs/cli"
  },
  "netlify": {
    "pros": [
      "Simple frontend hosting with serverless functions",
      "Generous free tier and easy setup",
      "Good Git-based continuous deployment"
    ],
    "cons": [
      "Function limits tighter than dedicated backends",
      "Less optimized for non-static heavy apps"
    ],
    "getStarted": "npm install -g netlify-cli"
  },
  "nextjs": {
    "pros": [
      "SSR, SSG, and routing built in",
      "The default React framework today",
      "Seamless full-stack with server actions"
    ],
    "cons": [
      "Opinionated, can feel heavy",
      "Best experience is tied to Vercel"
    ],
    "getStarted": "npx create-next-app@latest"
  },
  "nextjs-api": {
    "pros": [
      "Backend and frontend in one codebase",
      "Route Handlers and Server Actions built in",
      "Single deploy, great TypeScript end-to-end"
    ],
    "cons": [
      "Coupled to Next.js and its hosting model",
      "Long-running or heavy workloads fit poorly"
    ],
    "getStarted": "npx create-next-app@latest"
  },
  "node-cli": {
    "pros": [
      "Familiar TypeScript and npm ecosystem",
      "Fast to build with Commander or oclif",
      "Easy distribution via npm registry"
    ],
    "cons": [
      "Requires Node runtime on user machines",
      "Slower startup than compiled binaries"
    ],
    "getStarted": "npm install commander"
  },
  "none-cache": {
    "pros": [
      "Zero added infrastructure or moving parts",
      "No cache-invalidation bugs to reason about",
      "Easy to add caching later when measured"
    ],
    "cons": [
      "Repeated expensive work hits databases and latency",
      "May need rework once real load arrives"
    ],
    "getStarted": ""
  },
  "none-vector": {
    "pros": [
      "Zero added complexity or cost",
      "Defers a real architectural decision",
      "Keeps the stack minimal early"
    ],
    "cons": [
      "No retrieval until you add one later",
      "Refactor needed when RAG becomes necessary"
    ],
    "getStarted": ""
  },
  "npm-dist": {
    "pros": [
      "Instant global reach via npm registry",
      "npx runs tools with no install",
      "Simple publishing workflow"
    ],
    "cons": [
      "Requires Node installed on the machine",
      "Supply-chain and versioning risks"
    ],
    "getStarted": "npm install -g <package>"
  },
  "nuxt": {
    "pros": [
      "Batteries-included Vue with SSR built in",
      "Strong conventions and auto-imports speed development",
      "Large module ecosystem covers common needs"
    ],
    "cons": [
      "Opinionated structure can feel like magic",
      "Tied to the Vue ecosystem"
    ],
    "getStarted": "npm create nuxt@latest my-app"
  },
  "ollama": {
    "pros": [
      "Run open models fully locally",
      "Simple API and one-line model pulls",
      "No per-token cost or data leaving machine"
    ],
    "cons": [
      "Needs capable hardware for large models",
      "Quality trails frontier hosted models"
    ],
    "getStarted": "curl -fsSL https://ollama.com/install.sh | sh"
  },
  "pgvector": {
    "pros": [
      "Vector search inside existing Postgres",
      "No separate database to operate",
      "Transactional consistency with your data"
    ],
    "cons": [
      "Scales worse than dedicated vector DBs",
      "Index tuning needed for large datasets"
    ],
    "getStarted": "CREATE EXTENSION vector;"
  },
  "phaser": {
    "pros": [
      "Mature 2D framework for the browser",
      "Pure JS/TS, easy web deployment",
      "Active community and rich plugins"
    ],
    "cons": [
      "2D-only, no native 3D support",
      "Performance limited by web platform"
    ],
    "getStarted": "npm create @phaserjs/game@latest"
  },
  "photon": {
    "pros": [
      "Battle-tested real-time multiplayer networking",
      "Built-in matchmaking and rooms",
      "Works across major engines"
    ],
    "cons": [
      "Costs scale with concurrent users",
      "Proprietary, vendor lock-in risk"
    ],
    "getStarted": ""
  },
  "pinecone": {
    "pros": [
      "Fully managed, scales to production",
      "Low-latency similarity search",
      "No infrastructure to maintain"
    ],
    "cons": [
      "Proprietary with ongoing hosting cost",
      "Vendor lock-in and data leaves premises"
    ],
    "getStarted": "pip install pinecone"
  },
  "planetscale": {
    "pros": [
      "Serverless scaling for MySQL and Postgres",
      "Branching workflow for safe schema changes",
      "Strong performance with Vitess sharding"
    ],
    "cons": [
      "No free tier, paid from start",
      "Some MySQL features restricted by Vitess"
    ],
    "getStarted": "pscale auth login"
  },
  "playfab": {
    "pros": [
      "Managed backend for game live-ops",
      "Leaderboards, economy, and analytics included",
      "Free tier suits small titles"
    ],
    "cons": [
      "Microsoft-hosted, vendor lock-in",
      "Complex feature surface to learn"
    ],
    "getStarted": "dotnet add package PlayFabAllSDK"
  },
  "postgres": {
    "pros": [
      "Powerful, reliable, standards-compliant relational database",
      "Rich features: JSON, extensions, full-text search",
      "Sensible default for most applications"
    ],
    "cons": [
      "Tuning and ops require some expertise",
      "Heavier than embedded options for tiny apps"
    ],
    "getStarted": "docker run --name pg -e POSTGRES_PASSWORD=pass -p 5432:5432 -d postgres"
  },
  "powersync": {
    "pros": [
      "True offline-first local SQLite on device",
      "Syncs cleanly to your existing Postgres",
      "Reactive queries keep UI live"
    ],
    "cons": [
      "Extra sync service to run and configure",
      "Conflict handling needs deliberate design"
    ],
    "getStarted": "npm i @powersync/web"
  },
  "pypi": {
    "pros": [
      "Standard channel reaching nearly every Python user",
      "pipx isolates CLI tools from system Python",
      "Trivial install via pip or pipx"
    ],
    "cons": [
      "Native dependencies and wheels can complicate publishing",
      "Name squatting and supply-chain risks on public index"
    ],
    "getStarted": "pipx install <package>"
  },
  "python": {
    "pros": [
      "Highly readable, fast to write",
      "Dominant ecosystem for data and ML",
      "Huge standard library and packages"
    ],
    "cons": [
      "Slow runtime versus compiled languages",
      "Packaging and environments historically messy"
    ],
    "getStarted": "uv python install"
  },
  "pytorch": {
    "pros": [
      "Leading deep-learning framework for research",
      "Pythonic, dynamic, easy to debug",
      "Massive ecosystem and model availability"
    ],
    "cons": [
      "GPU setup and CUDA can frustrate",
      "Heavier than classic ML for tabular"
    ],
    "getStarted": "pip install torch"
  },
  "qt": {
    "pros": [
      "Mature, truly native cross-platform UI",
      "Excellent performance and rich widget set",
      "Strong tooling with Qt Creator"
    ],
    "cons": [
      "Commercial license needed for closed-source apps",
      "Steep C++ learning curve"
    ],
    "getStarted": "pip install pyside6"
  },
  "railway": {
    "pros": [
      "Deploy app and database together easily",
      "Minimal setup with sensible defaults",
      "Good for full-stack and background services"
    ],
    "cons": [
      "Usage-based pricing can surprise you",
      "Less global edge reach than rivals"
    ],
    "getStarted": "npm i -g @railway/cli"
  },
  "react-context": {
    "pros": [
      "Built into React, zero dependencies to add",
      "Perfect for light, low-frequency shared state",
      "Trivial to learn and reason about"
    ],
    "cons": [
      "Re-renders all consumers on any value change",
      "Not built for high-frequency server-state caching"
    ],
    "getStarted": ""
  },
  "react-vite": {
    "pros": [
      "Lightning-fast dev server and HMR",
      "Full React ecosystem with zero lock-in",
      "Simple SPA setup, no framework opinions"
    ],
    "cons": [
      "No built-in SSR or routing",
      "You assemble routing, data, and auth yourself"
    ],
    "getStarted": "npm create vite@latest my-app -- --template react-ts"
  },
  "redis": {
    "pros": [
      "Microsecond in-memory reads and writes",
      "Great for caching, sessions, queues",
      "Versatile data structures and pub/sub"
    ],
    "cons": [
      "Memory-bound, so data size costs money",
      "Durability needs careful persistence tuning"
    ],
    "getStarted": "npm i redis"
  },
  "redux-toolkit": {
    "pros": [
      "Structured, predictable state at scale",
      "Great DevTools and time-travel debugging",
      "Cuts most classic Redux boilerplate"
    ],
    "cons": [
      "Heavier and more verbose than alternatives",
      "Overkill for small or simple apps"
    ],
    "getStarted": "npm install @reduxjs/toolkit react-redux"
  },
  "render": {
    "pros": [
      "Simple cloud for web services and databases",
      "Straightforward Git-based deploys",
      "Managed Postgres and background workers included"
    ],
    "cons": [
      "Free instances sleep and cold-start slowly",
      "Fewer regions than hyperscale providers"
    ],
    "getStarted": "npm install -g render-cli"
  },
  "rust": {
    "pros": [
      "Memory safety without a garbage collector",
      "Top-tier performance and control",
      "Fearless concurrency, strong tooling"
    ],
    "cons": [
      "Steep learning curve, borrow checker",
      "Longer compile times"
    ],
    "getStarted": "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  },
  "s3": {
    "pros": [
      "Cheap, durable storage at any scale",
      "Ideal for assets, data lakes, backups",
      "Ubiquitous tooling and SDK support"
    ],
    "cons": [
      "Not a database, no querying",
      "Per-request and egress costs add up"
    ],
    "getStarted": "npm i @aws-sdk/client-s3"
  },
  "shadcn": {
    "pros": [
      "You own and can fully customize components",
      "Accessible, built on Radix and Tailwind",
      "No runtime dependency or version lock-in"
    ],
    "cons": [
      "You maintain copied component code yourself",
      "Requires Tailwind and React already set up"
    ],
    "getStarted": "npx shadcn@latest init"
  },
  "sklearn": {
    "pros": [
      "Reliable classic ML for tabular data",
      "Consistent, clean estimator API",
      "Excellent docs and broad algorithm coverage"
    ],
    "cons": [
      "No deep learning or GPU acceleration",
      "Scales poorly to very large datasets"
    ],
    "getStarted": "pip install scikit-learn"
  },
  "spark": {
    "pros": [
      "Scales data processing across many machines",
      "Unified batch, streaming, and SQL APIs",
      "Mature ecosystem with PySpark and MLlib"
    ],
    "cons": [
      "Heavy cluster setup and JVM overhead",
      "Overkill for data that fits one machine"
    ],
    "getStarted": "pip install pyspark"
  },
  "spring-boot": {
    "pros": [
      "Mature, battle-tested JVM ecosystem",
      "Rich enterprise features and integrations",
      "Strong tooling and long-term support"
    ],
    "cons": [
      "Verbose with heavier memory footprint",
      "Steep learning curve and slower startup"
    ],
    "getStarted": "spring init --dependencies=web my-app"
  },
  "sqlite": {
    "pros": [
      "Zero config, runs as a single file",
      "Extremely fast for local and edge reads",
      "No server to operate or maintain"
    ],
    "cons": [
      "Limited concurrent writers under heavy load",
      "Not built for multi-node distributed scaling"
    ],
    "getStarted": ""
  },
  "steam": {
    "pros": [
      "Largest PC gaming audience and storefront",
      "Built-in achievements, cloud saves, multiplayer",
      "Powerful wishlist and discovery features"
    ],
    "cons": [
      "100 USD per-title Steam Direct fee",
      "Takes a 30 percent revenue cut"
    ],
    "getStarted": "https://partner.steamgames.com"
  },
  "streamlit": {
    "pros": [
      "Python script becomes a web app instantly",
      "No frontend or HTML knowledge needed",
      "Huge widget library and active community"
    ],
    "cons": [
      "Reruns whole script on every interaction",
      "Not ideal for high-traffic production apps"
    ],
    "getStarted": "pip install streamlit"
  },
  "supabase": {
    "pros": [
      "Postgres, auth, storage, realtime without a server",
      "Instant APIs and row-level security",
      "Generous free tier and great DX"
    ],
    "cons": [
      "Vendor lock-in around its platform",
      "Less control than a custom backend"
    ],
    "getStarted": "npx supabase init"
  },
  "supabase-auth": {
    "pros": [
      "Auth tied directly to your Postgres",
      "Row-level security enforces access at database",
      "Generous free tier with social logins"
    ],
    "cons": [
      "Best value only inside the Supabase ecosystem",
      "RLS policies have a real learning curve"
    ],
    "getStarted": "npm install @supabase/supabase-js @supabase/ssr"
  },
  "supabase-db": {
    "pros": [
      "Managed Postgres with instant REST APIs",
      "Realtime subscriptions and row-level security",
      "Generous free tier and great DX"
    ],
    "cons": [
      "Heavy reliance on RLS policy correctness",
      "Less control than self-hosted Postgres"
    ],
    "getStarted": "npx supabase init"
  },
  "sveltekit": {
    "pros": [
      "Compile-time output means tiny runtime",
      "Excellent developer experience and ergonomics",
      "Built-in SSR, routing, and data loading"
    ],
    "cons": [
      "Smaller ecosystem and hiring pool than React",
      "Fewer third-party component libraries available"
    ],
    "getStarted": "npx sv create my-app"
  },
  "swift": {
    "pros": [
      "Best language for Apple platforms",
      "Safe, modern, expressive syntax",
      "Now viable for server and cross-platform"
    ],
    "cons": [
      "Ecosystem still centered on Apple",
      "Tooling weaker off macOS"
    ],
    "getStarted": "brew install swiftly && swiftly init"
  },
  "swiftui": {
    "pros": [
      "Best possible native iOS look and feel",
      "Declarative UI with live Xcode previews",
      "Deep integration with Apple platform APIs"
    ],
    "cons": [
      "iOS and Apple platforms only",
      "Newer APIs gated behind recent OS versions"
    ],
    "getStarted": "xcode-select --install"
  },
  "tailwind": {
    "pros": [
      "Fast, consistent styling without leaving markup",
      "No naming or context-switching to CSS files",
      "Tiny production output via purging"
    ],
    "cons": [
      "Verbose, cluttered class lists in markup",
      "Learning curve for the utility vocabulary"
    ],
    "getStarted": "npm install tailwindcss @tailwindcss/vite"
  },
  "tanstack-query": {
    "pros": [
      "Removes most manual server-state code",
      "Caching, refetching, and sync built in",
      "Framework-agnostic with great DevTools"
    ],
    "cons": [
      "Not for client-only or local UI state",
      "Extra concept layer to learn"
    ],
    "getStarted": "npm install @tanstack/react-query"
  },
  "tauri": {
    "pros": [
      "Tiny binaries via system webview",
      "Secure Rust core with sandboxing",
      "Lower memory use than Electron"
    ],
    "cons": [
      "Webview rendering differs across platforms",
      "Smaller ecosystem and some Rust required"
    ],
    "getStarted": "npm create tauri-app@latest"
  },
  "threejs": {
    "pros": [
      "Most popular 3D library on the web",
      "Huge community and learning resources",
      "Flexible low-level WebGL/WebGPU control"
    ],
    "cons": [
      "Not a game engine, needs add-ons",
      "Verbose for complex scenes and physics"
    ],
    "getStarted": "npm install three"
  },
  "ts": {
    "pros": [
      "Catches type errors before runtime",
      "One language across frontend and backend",
      "Excellent editor autocomplete and refactoring"
    ],
    "cons": [
      "Adds a build/compile step",
      "Type gymnastics can get complex"
    ],
    "getStarted": "npm install -D typescript"
  },
  "typer": {
    "pros": [
      "Type hints define CLI args automatically",
      "Great autocompletion and help output",
      "Built on robust Click foundation"
    ],
    "cons": [
      "Requires Python runtime to run",
      "Python-only ecosystem"
    ],
    "getStarted": "pip install typer"
  },
  "unity": {
    "pros": [
      "Huge asset store and ecosystem",
      "Strong 2D and 3D support",
      "Ships to nearly every platform"
    ],
    "cons": [
      "Licensing and pricing history erodes trust",
      "C# runtime overhead versus native engines"
    ],
    "getStarted": ""
  },
  "unreal": {
    "pros": [
      "Industry-leading AAA visual fidelity",
      "Blueprints enable coding-light prototyping",
      "Powerful built-in tooling and Nanite"
    ],
    "cons": [
      "Heavy footprint and steep learning curve",
      "Overkill for simple 2D games"
    ],
    "getStarted": ""
  },
  "vercel": {
    "pros": [
      "Zero-config hosting tuned for Next.js",
      "Automatic preview deployments per branch",
      "Excellent edge network and developer experience"
    ],
    "cons": [
      "Costs can spike with heavy serverless usage",
      "Best fit mainly for frontend and Next.js"
    ],
    "getStarted": "npm i -g vercel"
  },
  "warehouse": {
    "pros": [
      "Queries huge datasets with plain SQL",
      "Fully managed, scales without ops",
      "Strong analytics and BI integrations"
    ],
    "cons": [
      "Costs can spike with careless queries",
      "Overkill for small datasets"
    ],
    "getStarted": "pip install google-cloud-bigquery"
  },
  "weaviate": {
    "pros": [
      "Hybrid vector plus keyword search",
      "Open source and self-hostable",
      "Built-in vectorizer modules"
    ],
    "cons": [
      "Operating a cluster adds ops burden",
      "Heavier than embedded stores"
    ],
    "getStarted": "docker run -p 8080:8080 cr.weaviate.io/semitechnologies/weaviate"
  },
  "zustand": {
    "pros": [
      "Tiny, minimal API with no boilerplate",
      "Works without context providers",
      "Easy to learn and adopt incrementally"
    ],
    "cons": [
      "Fewer conventions for very large apps",
      "No built-in server-state handling"
    ],
    "getStarted": "npm install zustand"
  }
};

const EMPTY: TechDetail = { pros: [], cons: [], getStarted: "" };

export function getDetail(techId: string): TechDetail {
  return DETAILS[techId] ?? EMPTY;
}
