import { CATALOG } from "./catalog";
import { getDetail } from "./details";
import { getCategory } from "./questions";
import type { Answers, CategoryId, Recommendation } from "./types";

const GENERIC_REASON = "A strong general-purpose choice for this layer";

/**
 * Score every candidate in every layer and build the recommendation.
 *
 * For each candidate: total = base + sum(boost.score) for boosts whose
 * `when(answers)` is true. The top scorer becomes the primary pick; the
 * reasons shown are the positive boosts that fired for it. The next two
 * candidates that scored above zero are offered as alternatives, and the
 * full ranked list is exposed for transparency.
 */
export function recommend(categoryId: CategoryId, answers: Answers): Recommendation {
  const category = getCategory(categoryId);
  if (!category) {
    throw new Error(`Unknown category: ${categoryId}`);
  }

  const layers = category.layers.map((layer) => {
    const scored = layer.candidates
      .map((candidate) => {
        const reasons: string[] = [];
        let score = candidate.base;
        for (const boost of candidate.boosts ?? []) {
          if (boost.when(answers)) {
            score += boost.score;
            // Surface the rationale for any boost that fires and carries text.
            // Penalty boosts (negative score) intentionally use an empty reason,
            // while an always-on note can use score 0 to add context without points.
            if (boost.score >= 0 && boost.reason) {
              reasons.push(boost.reason);
            }
          }
        }
        return { tech: candidate.tech, score, reasons };
      })
      // Stable, deterministic ordering: score desc, then declaration order.
      .map((entry, index) => ({ ...entry, index }))
      .sort((a, b) => b.score - a.score || a.index - b.index);

    const top = scored[0];
    const topTech = CATALOG[top.tech];
    const detail = getDetail(top.tech);
    const reasons = top.reasons.length > 0 ? top.reasons : [GENERIC_REASON];

    const alternatives = scored
      .slice(1)
      .filter((s) => s.score > 0)
      .slice(0, 2)
      .map((s) => ({ name: CATALOG[s.tech].name, url: CATALOG[s.tech].url }));

    const ranked = scored.map((s) => ({
      name: CATALOG[s.tech].name,
      url: CATALOG[s.tech].url,
      score: s.score,
    }));

    return {
      layer: layer.label,
      key: layer.key,
      primary: {
        name: topTech.name,
        blurb: topTech.blurb,
        url: topTech.url,
        reasons,
        pros: detail.pros,
        cons: detail.cons,
        getStarted: detail.getStarted,
        score: top.score,
      },
      alternatives,
      ranked,
    };
  });

  return {
    categoryId,
    categoryLabel: category.label,
    layers,
    summary: layers.map((l) => ({ layer: l.layer, tech: l.primary.name })),
  };
}

/** The non-empty getting-started commands for the recommended picks. */
export function scaffoldCommands(
  rec: Recommendation,
): { layer: string; name: string; command: string }[] {
  return rec.layers
    .filter((l) => l.primary.getStarted.trim().length > 0)
    .map((l) => ({ layer: l.layer, name: l.primary.name, command: l.primary.getStarted }));
}

/** Plain-text version of a recommendation, for copy-to-clipboard. */
export function recommendationToText(rec: Recommendation): string {
  const lines: string[] = [
    `Recommended stack — ${rec.categoryLabel}`,
    "",
    ...rec.summary.map((s) => `• ${s.layer}: ${s.tech}`),
    "",
    "Generated by TechStack Advisor",
  ];
  return lines.join("\n");
}

/** Markdown version of a recommendation, for export/download. */
export function recommendationToMarkdown(rec: Recommendation): string {
  const lines: string[] = [`# Recommended stack — ${rec.categoryLabel}`, ""];

  lines.push("| Layer | Pick |", "| --- | --- |");
  for (const s of rec.summary) lines.push(`| ${s.layer} | ${s.tech} |`);
  lines.push("");

  for (const layer of rec.layers) {
    lines.push(`## ${layer.layer}: [${layer.primary.name}](${layer.primary.url})`, "");
    lines.push(`${layer.primary.blurb}`, "");
    if (layer.primary.reasons.length) {
      lines.push("**Why:**");
      for (const r of layer.primary.reasons) lines.push(`- ${r}`);
      lines.push("");
    }
    if (layer.primary.pros.length) {
      lines.push("**Strengths:** " + layer.primary.pros.join(" · "), "");
    }
    if (layer.primary.cons.length) {
      lines.push("**Watch-outs:** " + layer.primary.cons.join(" · "), "");
    }
    if (layer.primary.getStarted) {
      lines.push("```bash", layer.primary.getStarted, "```", "");
    }
    if (layer.alternatives.length) {
      lines.push(
        "_Also consider: " +
          layer.alternatives.map((a) => `[${a.name}](${a.url})`).join(", ") +
          "_",
        "",
      );
    }
  }

  const scaffold = scaffoldCommands(rec);
  if (scaffold.length) {
    lines.push("## Getting started", "", "```bash");
    for (const s of scaffold) lines.push(`# ${s.name}`, s.command);
    lines.push("```", "");
  }

  lines.push("---", "_Generated by TechStack Advisor_");
  return lines.join("\n");
}
