// Reads the generate-tech-details workflow output and emits lib/details.ts.
// Usage: node scripts/gen-details.mjs <path-to-output-json>
import fs from "node:fs";
import path from "node:path";

const src = process.argv[2];
if (!src) {
  console.error("Pass the workflow output file path as the first argument.");
  process.exit(1);
}

const raw = fs.readFileSync(src, "utf8");
const parsed = JSON.parse(raw);
const details = (parsed.result && parsed.result.details) || parsed.details;
if (!details) {
  console.error("No details found in output.");
  process.exit(1);
}

// Undo any HTML-entity escaping that may have leaked into strings.
function clean(v) {
  if (typeof v === "string") {
    return v
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .trim();
  }
  if (Array.isArray(v)) return v.map(clean);
  if (v && typeof v === "object") {
    const o = {};
    for (const k of Object.keys(v)) o[k] = clean(v[k]);
    return o;
  }
  return v;
}

const cleaned = {};
for (const id of Object.keys(details).sort()) {
  const d = details[id];
  cleaned[id] = {
    pros: clean(d.pros ?? []),
    cons: clean(d.cons ?? []),
    getStarted: clean(d.getStarted ?? ""),
  };
}

const body = `import type { TechDetail } from "./types";

/**
 * Reference content (pros / cons / getting-started) for each catalog tech,
 * keyed by the same id used in catalog.ts. Generated by the
 * generate-tech-details workflow (see scripts/gen-details.mjs).
 * Missing ids fall back to empty detail via getDetail().
 */
export const DETAILS: Record<string, TechDetail> = ${JSON.stringify(cleaned, null, 2)};

const EMPTY: TechDetail = { pros: [], cons: [], getStarted: "" };

export function getDetail(techId: string): TechDetail {
  return DETAILS[techId] ?? EMPTY;
}
`;

const out = path.join(process.cwd(), "lib", "details.ts");
fs.writeFileSync(out, body, "utf8");
console.log(`Wrote ${Object.keys(cleaned).length} entries to ${out}`);
